  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-app
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - STREAMLIT_SERVER_ENABLECORS=false
      - STREAMLIT_SERVER_HEADLESS=true
    ports:
      - "8501:8501"
    depends_on:
      - ollama
      - redis
      - qdrant
    restart: unless-stopped
    command: >
      bash -c "
      echo 'Pulling phi3:mini model...';
      ollama pull phi3:mini || true;
      echo 'Starting Streamlit...';
      streamlit run app.py --server.port=8501 --server.address=0.0.0.0
      "
