version: '3.9'

services:
  redis:
    image: redis:7
    container_name: chatbot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  qdrant:
    image: qdrant/qdrant:dev
    container_name: chatbot-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    container_name: chatbot-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-app
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - STREAMLIT_SERVER_ENABLECORS=false
      - STREAMLIT_SERVER_HEADLESS=true
    ports:
      - "8501:8501"
    depends_on:
      - ollama
      - redis
      - qdrant
    restart: unless-stopped

volumes:
  redis-data:
  qdrant-data:
  ollama-data:
